project:
  type: book
  output-dir: _book

book:
  title: "Power and Sample Size in R"
  author: "Clay Ford, Lauren Brideau, and Ethan Kadiyala"
  date: last-modified
  chapters:
    - index.qmd
    - t_tests.qmd
    - p_tests.qmd
    - anova.qmd
    - regression.qmd
    - mixed.qmd
    - tips.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand




